[package]
name = "guan"
version = "0.1.0"
authors = ["Jan Soendermann <jan.soendermann+git@gmail.com>"]
edition = "2018"

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.8"
clap = "2"